### ISSUE TITLE
7.1.2 Crashes due to an error in copy-pasted code

### ISSUE THREAD

**Issue by justjanne** [nanos/FediFetcher#132]
https://github.com/nanos/FediFetcher/blob/3651d028a6a6c703bb731693cf70bc1d10ea460c/find_posts.py#L743

```python
Traceback (most recent call last):
  File "/app/find_posts.py", line 1521, in <module>
    context_urls = get_all_context_urls(arguments.server, replied_toot_ids, seen_hosts)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/find_posts.py", line 756, in get_all_context_urls
    if(toot_context_should_be_fetched(toot)):
                                      ^^^^
NameError: name 'toot' is not defined
```

**Comment by nanos** [comment]
I believe this has been fixed in this commit: https://github.com/nanos/FediFetcher/commit/e7da9a1f619293207f581aa096afe364eab68002

can you confirm please?
